//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRegistration.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public string FunctionName { get; set; }
        public string InputData { get; set; }
        public string OutputData { get; set; }
        public Nullable<int> UserId { get; set; }
        public string GroupType { get; set; }
        public string FullErrorDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
