//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRegistration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserHobby
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int HobbyID { get; set; }
    
        public virtual tblHobby tblHobby { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
